//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyProjectManagementService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolicyProjectEntities : DbContext
    {
        public PolicyProjectEntities()
            : base("name=PolicyProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_activity_log> tbl_activity_log { get; set; }
        public DbSet<tbl_event> tbl_event { get; set; }
        public DbSet<tbl_group> tbl_group { get; set; }
        public DbSet<tbl_login> tbl_login { get; set; }
        public DbSet<tbl_policy> tbl_policy { get; set; }
        public DbSet<tbl_policy_set> tbl_policy_set { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<tbl_device_info> tbl_device_info { get; set; }
        public DbSet<tbl_platform> tbl_platform { get; set; }
        public DbSet<tbl_login_devices> tbl_login_devices { get; set; }
    }
}
