//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyProjectManagementService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_activity_log
    {
        public long id { get; set; }
        public System.DateTime log_date { get; set; }
        public int id_event { get; set; }
        public Nullable<long> id_document { get; set; }
        public string message { get; set; }
        public string device { get; set; }
        public string login { get; set; }
    }
}
