//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyProjectManagementService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        public long id { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public string certificate { get; set; }
        public long id_user { get; set; }
        public int id_group { get; set; }
    }
}
