//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyProjectManagementService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_policy_set
    {
        public long id { get; set; }
        public Nullable<int> id_group { get; set; }
        public int id_policy { get; set; }
        public Nullable<long> id_login { get; set; }
        public Nullable<bool> selected { get; set; }
        public string policy_param { get; set; }
    }
}
