//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyProjectManagementService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_device_info
    {
        public long id { get; set; }
        public string device_name { get; set; }
        public string device_serial_number { get; set; }
        public string device_ip_addr { get; set; }
        public string device_mac_addr { get; set; }
        public short device_platform_id { get; set; }
    }
}
