//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyProjectManagementService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_policy
    {
        public int id { get; set; }
        public string policy_name { get; set; }
        public Nullable<short> platform_id { get; set; }
        public string policy_instruction { get; set; }
        public string policy_default_param { get; set; }
    }
}
