//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyProjectManagementService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login_devices
    {
        public long id { get; set; }
        public long id_login { get; set; }
        public long id_device { get; set; }
        public Nullable<bool> need_update_device { get; set; }
    }
}
